columns = [
    "Company Name",
    "Job Title",
    "Link",
    "Status",
    "Applied",
    "Application Method",
    "Application Date",
    "Contact Person",
    "Cold Email Sent",
    "Notes",
    "Next Steps",
  ]

data = [
    [
      "Acme Corp",
      "Software Engineer",
      "https://acme.com/jobs/123",
      "Pending",
      "Yes",
      "Online",
      "2024-01-10",
      "John Smith",
      "Yes",
      "Hiring manager seemed interested.",
      "Prepare for potential interview",
    ],
    [
      "Stark Industries",
      "Product Manager",
      "https://starkindustries.com/careers",
      "Applied",
      "No",
      "Referral",
      "",
      "Pepper Potts",
      "No",
      "Reach out to Pepper for referral.",
      "Contact Pepper",
    ],
    [
      "Wayne Enterprises",
      "Marketing Analyst",
      "https://wayneenterprises.com/jobs",
      "Interviewing",
      "Yes",
      "Job Board",
      "2024-01-15",
      "",
      "Yes",
      "Interview scheduled for next week.",
      "Review company portfolio",
    ],
    [
      "Cyberdyne Systems",
      "Data Scientist",
      "https://cyberdyne.com/join-us",
      "Not Applied",
      "No",
      "",
      "",
      "",
      "No",
      "Research company further.",
      "Check employee reviews",
    ],
    [
      "Umbrella Corporation",
      "Researcher",
      "https://umbrellacorp.net/careers",
      "Interested",
      "No",
      "",
      "",
      "",
      "No",
      "Potential ethical concerns.",
      "Investigate company reputation",
    ],
    [
      ("Acme Corp",
      "Software Engineer",
      "https://acme.com/jobs/123",
      "Pending",
      "Yes",
      "Online",
      "2024-01-10",
      "John Smith",
      "Yes",
      "Hiring manager seemed interested.",
      "Prepare for potential interview"),
    ],
    [
      "Stark Industries",
      "Product Manager",
      "https://starkindustries.com/careers",
      "Applied",
      "No",
      "Referral",
      "",
      "Pepper Potts",
      "No",
      "Reach out to Pepper for referral.",
      "Contact Pepper",
    ],
    [
      "Wayne Enterprises",
      "Marketing Analyst",
      "https://wayneenterprises.com/jobs",
      "Interviewing",
      "Yes",
      "Job Board",
      "2024-01-15",
      "",
      "Yes",
      "Interview scheduled for next week.",
      "Review company portfolio",
    ],
    [
      "Cyberdyne Systems",
      "Data Scientist",
      "https://cyberdyne.com/join-us",
      "Not Applied",
      "No",
      "",
      "",
      "",
      "No",
      "Research company further.",
      "Check employee reviews",
    ],
    [
      "Umbrella Corporation",
      "Researcher",
      "https://umbrellacorp.net/careers",
      "Interested",
      "No",
      "",
      "",
      "",
      "No",
      "Potential ethical concerns.",
      "Investigate company reputation",
    ],
  ]

from deta import Deta
deta = Deta()
db = deta.Base("jobs_applied")
new_columns = [c.lower().replace(' ', '_') for c in columns]
for d in data:
    my_job = dict(zip(new_columns, d))
    print('my_job: ', my_job)
    db.put(my_job)
    print()